name : Workflow for running in diff OS

on:
 push
 
jobs:
 run-on-ubuntu-machine:
  runs-on: ubuntu-latest
  steps:
    - run : echo "It is running on $RUNNER_OS"
 run-on-windows-machine:
  runs-on: windows-latest
  steps:
    - name : shell
      shell: bash
      run : echo "It is running on $RUNNER_OS"
  
