name : Workflow for Actions for Java setup and maven

on:
 push
 
jobs:
 echo_javasetup:
  runs-on: ubuntu-latest
  steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
     - run: mvn --batch-mode --update-snapshots verify
     - run: mkdir staging && cp target/*.jar staging
     - uses: actions/upload-artifact@v4
       with:
        name: Package
        path: staging
